field: 61c770c0-be33-458a-9755-01f2673b610f # Partner Specialty List
fieldLayouts:
  16fc8906-4f1f-4cd8-8648-d978daff709a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 73af2105-1d51-4e4e-96a1-9558e8db0e59 # Specialty Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce7bca0c-3265-4e29-9b64-c5dd8e912547
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8309aa76-d1fd-470e-825f-c8c8cee62520
        userCondition: null
fields:
  73af2105-1d51-4e4e-96a1-9558e8db0e59: # Specialty Name
    columnSuffix: oeasvaij
    contentColumnType: text
    fieldGroup: null
    handle: specialtyName
    instructions: null
    name: 'Specialty Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: specialty
name: Specialty
sortOrder: 1
