fieldLayouts:
  19119b61-b024-4b21-9464-bd412d2dfcdb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a031baa2-5a8e-42e2-a28b-7667ec3321a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72ed4295-6ee7-4011-9f92-bc5016b964f1
        userCondition: null
fs: images
handle: assets
name: Assets
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
