columnSuffix: muinyycb
contentColumnType: text
fieldGroup: c076d11d-e684-47f3-ba8a-392b06089feb # Contact Information
handle: emailAddress
instructions: 'Email address for company'
name: 'General Email Address'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
