columnSuffix: dnjkcvzj
contentColumnType: text
fieldGroup: 628725c0-4b0e-4e0e-9832-8075bbbb283b # Partner
handle: partneremail
instructions: null
name: 'Partner Email'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
