columnSuffix: valutxyx
contentColumnType: boolean
fieldGroup: 628725c0-4b0e-4e0e-9832-8075bbbb283b # Partner
handle: partnerDesignatedMember
instructions: 'Is this partner a Designated Member of the Appraisal Institute?'
name: 'Partner Designated Member'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
