columnSuffix: avybcdzi
contentColumnType: text
fieldGroup: eee713d3-b3ed-454c-a580-a6176331f333 # Staff
handle: staffPosition
instructions: 'Staff member''s job title'
name: 'Staff Position'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
