columnSuffix: null
contentColumnType: string
fieldGroup: eee713d3-b3ed-454c-a580-a6176331f333 # Staff
handle: staffImage
instructions: null
name: 'Staff Image'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:f31feac0-b14a-4ec9-a0e4-ee6405efad6e' # Images
  defaultUploadLocationSubpath: partners/staff
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:f31feac0-b14a-4ec9-a0e4-ee6405efad6e' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:f31feac0-b14a-4ec9-a0e4-ee6405efad6e' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
