defaultPlacement: end
enableVersioning: true
handle: newsletters
name: Newsletters
propagationMethod: all
siteSettings:
  ed37deb3-bb5a-484b-8ba0-1c3b2ef5700c: # acg4
    enabledByDefault: true
    hasUrls: true
    template: newsletters/_entry
    uriFormat: 'newsletters/{slug}'
type: channel
