defaultPlacement: end
enableVersioning: true
handle: partnerWelcome
name: 'Partner Welcome'
propagationMethod: all
siteSettings:
  ed37deb3-bb5a-484b-8ba0-1c3b2ef5700c: # acg4
    enabledByDefault: true
    hasUrls: true
    template: partner-welcome/_entry
    uriFormat: partner-welcome
type: single
