defaultPlacement: end
enableVersioning: true
handle: partners
name: Partners
propagationMethod: all
siteSettings:
  ed37deb3-bb5a-484b-8ba0-1c3b2ef5700c: # acg4
    enabledByDefault: true
    hasUrls: true
    template: partners/_entry
    uriFormat: 'partner-detail/{slug}'
structure:
  maxLevels: null
  uid: cc5b5845-0d40-474b-aa6e-620903b98c34
type: structure
