defaultPlacement: end
enableVersioning: true
handle: staff
name: Staff
propagationMethod: all
siteSettings:
  ed37deb3-bb5a-484b-8ba0-1c3b2ef5700c: # acg4
    enabledByDefault: true
    hasUrls: true
    template: staff/_entry
    uriFormat: 'staff/{slug}'
structure:
  maxLevels: null
  uid: 1867bd7f-b1db-46bd-8527-89ff4a520f71
type: structure
